name: Vitest
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Prendre le code en local
        run: git clone https://github.com/quemet/Vitest.git
      - name: Installe les dépendances
        run: npm install
      - name: run les tests avec vitest
        run: npm test
      - name: Message de confirmation
        run: echo "Tout c'est bien passé"
